### ISSUE TITLE
Text is not persevered when opening the editor

### ISSUE THREAD

**Issue by Hund** [keith/edit-weechat#1]
I just wrote some text and decided to use my editor Vim to complete the text in, but when I opened my editor the text was gone.

The expected behaviour should be that the text id preserved when opening the editor.

**Comment by keith** [comment]
How did you execute `/edit` if you had already typed text?

**Comment by Hund** [comment]
A keybinding. I'm not a savage. :)

**Comment by keith** [comment]
Haha, I hadn't handled that case, can you submit a PR with the fix? I'd happily merge it!

**Comment by Hund** [comment]
Sure! Just give me some time to learn Python first. ;P I looked at the code but my programming skills is very limited, if I knew how to solve it, I would have started out with a pull request and not just whine about it here. :)

**Comment by keith** [comment]
Fixed in https://github.com/keith/edit-weechat/pull/2

**Comment by Hund** [comment]
Thanks! It works great. :)
