### ISSUE TITLE
python: stdout/stderr (slack): WS ERROR

### ISSUE THREAD

**Issue by fluxsauce** [keith/edit-weechat#3]
Using `/edit` with WeeChat 2.1, wee-slack v2.0.0, Python 2.7.14 and `nano` on macOS 10.13.4 and get

```
python: stdout/stderr (slack): WS ERROR
```

when trying to send any message, composed in edit or not.

**Comment by sQVe** [comment]
@fluxsauce You can find more information about this issue here: https://github.com/wee-slack/wee-slack/issues/676

I suggest closing this issue as it is not related to `edit-weechat`.

**Comment by keith** [comment]
Thanks @sQVe !
