### ISSUE TITLE
Weechat timeout

### ISSUE THREAD

**Issue by sQVe** [keith/edit-weechat#5]
_Thank you for developing this plugin, it's pretty awesome._

I wrote a really long message today in `/edit` and got `disconnected` when returning to `weechat`. I got annoyed because I lost that long message and started to investigate what the actual problem was. It seems like as soon as I have `/edit` open `> 5 minutes` `weechat` times out. I can reproduce this pretty consistently.

Is there any way to solve this? My weechat config is located here: https://github.com/sQVe/dotfiles/tree/master/weechat

**Comment by keith** [comment]
Hmm interesting. It must have something to do with weechat being backgrounded. There must be a setting for this timeout if it's as specific as 5 minutes.

**Comment by sQVe** [comment]
@keith I would believe so. I've tried tinkering with obvious `timeout` settings in `weechat` but I'm falling short. I'm not 100% certain on the accuracy of `> 5 minutes` but it seems pretty close at least.

**Comment by sQVe** [comment]
@keith Would it be possible to open the `$EDITOR` in a new process/window instead of putting `weechat` in the background? This would atleast allow me to test if this is the issue, which it very likely is.

**Comment by sQVe** [comment]
I've researched this further and asked around at both #python and #weechat. As soon as we wait for the subprocess we essentially stop weechat. When the server then sends a ping to the client it will not respond and you'll get disconnected.

The time, around 5 minutes, mentioned above was just a coincidence. I've replicated this with just Vim open for a short while.

This plugin is, in its current state, quite broken. The README should probably note this issue.

**Comment by keith** [comment]
If you have a solution with another approach feel free to submit a PR


--
Keith Smiley

**Comment by sQVe** [comment]
@poljar Is there a reason for you not creating a PR for the fix referenced above?

**Comment by poljar** [comment]
I wanted to make it work inside tmux as well, but since the editor ends up being a child of tmux instead of Weechat it proved to be tricky.

So that's still somewhat a work in progress.

**Comment by sQVe** [comment]
@poljar Could we not seperate those two things though? I run `i3wm` so I have no need for `tmux` support but would love this plugin to properly work. I'm trying your implementation as-we-speak.

**Comment by poljar** [comment]
Of course, those are already separate patches.

**Comment by sQVe** [comment]
@poljar Your fix has been working nicely so far. Nice work! I suggest making a **PR**! :+1:
